# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-04-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210421_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_pic',
            field=models.ImageField(blank=True, upload_to='blog_pics'),
        ),
    ]
