# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210424_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.IntegerField(default=63),
        ),
    ]
