# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2021-08-09 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_post_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stars',
        ),
        migrations.AddField(
            model_name='post',
            name='stars',
            field=models.ManyToManyField(default=63, to=settings.AUTH_USER_MODEL),
        ),
    ]
